name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  doxygen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Doxygen Action
      # You may pin to the exact commit or the version.
      # uses: mattnotmitt/doxygen-action@cdd5472f8e48e141b89d2633c1ae72991a21cb6a
        uses: mattnotmitt/doxygen-action@1.9.2
        with:
          # Path to Doxyfile
          doxyfile-path: ./Doxyfile
          # Working directory
          working-directory: .
